spring.application.name=servicediscovery
server.port=8761

eureka.client.registerWithEureka=false
eureka.client.fetchingRegistry=false
eureka.server.enableReplication=false
eureka.instance.homePageUrl=https://localhost:8761/